[package]
name = "sound_space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.1"
serde = { version = "1.0.154", features = ["derive"] }
serde_derive = "1.0.154"
serde_json = "1.0.94"
